package com.sbg.bdd.wiremock.scoped.cdi;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;

/**
 * This class was generated by Apache CXF 3.2.0-SNAPSHOT-a55635031f4e86124269df880bd3182b1b2dd78d
 * 2017-08-29T07:21:08.336+02:00
 * Generated source version: 3.2.0-SNAPSHOT
 * 
 */
@WebService(targetNamespace = "http://www.examples.com/wsdl/HelloService.wsdl", name = "Hello_PortType")
@SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
public interface HelloPortType {

    @WebMethod(action = "sayHello")
    @WebResult(name = "greeting", targetNamespace = "", partName = "greeting")
    public String sayHello(
            @WebParam(partName = "firstName", name = "firstName", targetNamespace = "")
                    String firstName
    );
}
